const DISCORD_API_BASE_URL = "https://discord.com/api/v10";

const DISCORD_APPLICATION_ID = process.env.DISCORD_APPLICATION_ID;
const DISCORD_BOT_TOKEN = process.env.DISCORD_BOT_TOKEN;
const DISCORD_PUBLIC_KEY = process.env.DISCORD_PUBLIC_KEY;
const DISCORD_GUILD_ID = process.env.DISCORD_GUILD_ID;

export {
  DISCORD_API_BASE_URL,
  DISCORD_APPLICATION_ID,
  DISCORD_BOT_TOKEN,
  DISCORD_PUBLIC_KEY,
  DISCORD_GUILD_ID,
};
    